apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-changes-alerts
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
    - name: ksecwatch-pod-alerts
      rules:

        - alert: PodRestartingFrequently
          expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
          for: 1m
          labels:
            severity: warning
            team: sre
            category: pods
            project: ksecwatch
          annotations:
            description: "Pod is restarting frequently."

        - alert: PodNotReady
          expr: kube_pod_status_ready{condition="true"} == 0
          for: 1m
          labels:
            severity: critical
            team: sre
            category: pods
            project: ksecwatch
          annotations:
            description: "Pod is not ready for at least 1 minute."
