apiVersion: v1
kind: Service
metadata:
  name: ksecwatch-svc
  namespace: monitoring
  labels:
    app: ksecwatch
spec:
  type: ClusterIP
  selector:
    app: ksecwatch
  ports:
    - name: http
      port: 8000
      targetPort: 8000
